theme: jekyll-theme-minimal
title: Ayumu Tanaka
description: Associate Professor, College of Economics, Aoyama Gakuin University, Tokyo, Japan
logo: /river.jpg
ORCID: https://orcid.org/0000-0001-9858-9236
