---
title: Rメモ
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "figures/fig-",
  out.width = "100%",
  dpi = 300
)
```


# `$`と`[[]]`の使い方

- `$`と`[[]]`のいずれを使っても、データの中の特定の変数を指定できる。
- どちらもBase Rのオペレーター。
- 既存変数の対数を作成する例。
- `[[]]`を使う場合、変数名を引用符で囲む必要があることに注意。例）"wage"

```{r}
# AERパッケージのデータを使う
library(AER)
data("CPS1985")

# `$`を用いた変数の指定
CPS1985$lnwage1 = log(CPS1985$wage)

head(CPS1985$lnwage1)

# [[]]を用いた変数の指定
CPS1985[["lnwage2"]] = log(CPS1985[["wage"]])

head(CPS1985$lnwage2)
```

# 複数の変数の対数をとる。

```{r}
# 既存データを一旦削除
rm(list =ls())

# AERパッケージのデータを使う
library(AER)
data("CPS1985")

# 対数変換したい変数のリスト
variables <- c("age", "wage")

for (var in variables) {
  # 新しい変数名
  new_var_name <- paste0("ln", var) 
  # 対数変換
  CPS1985[[new_var_name]] <- log(CPS1985[[var]])
}

head(CPS1985$lnwage)

head(CPS1985$lnage)

#CPS1985 <- data.frame(CPS1985) 
```



# Rマークダウンからマークダウンを生成

YAMLの例

```
---
title: Rメモ
output: github_document
---

```

# グローバルチャンクの例

```

knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "figures/fig-",
  out.width = "100%",
  dpi = 300
  )

```

```
knitr::opts_chunk$set(echo = TRUE, #コードを表示
                      cache = FALSE, #キャッシュを残さない
                      fig.path = "figures/fig-",
                      out.width = "100%",
                      dpi = 300,
                      message=FALSE, warning=FALSE)
```

# パイプ・オペレータの使い方

```{r}
1+1

a <- 1:3 |> sum()

a
```


# グラフ作成・保存の基本

```{r plot}
plot(1:5, 6:10)

```

```{r, ggplot}
library(dplyr)

state <- state.x77

library(ggplot2)
ggplot(data = state) +
  geom_point(mapping = aes(x = Income, y = Population) )


```


# 回帰分析

```
install.packages("wooldridge")
install.packages("AER")

```


```{r}
library(wooldridge)

data("wage1")
wageModel <- lm(lwage ~ educ + exper + tenure, data = wage1)

summary(wageModel)
```

