---
title: "2022「公共地域政策論（国際）」"
author: "Ayumu Tanaka"
date: '2022-06-14'
output:
  html_document: default
---

# 棒グラフと散布図

```{r}
library(readxl)
asia <- read_excel("asia.xlsx")
barplot(asia$ctfp,names.arg = asia$countrycode)
barplot(asia$pop,names.arg=asia$countrycode)


plot(asia$pop,asia$rgdpe)
plot(asia$pop,asia$rgdpe,log="xy")
plot(asia$pop,asia$rgdpe,log="xy",pch=4)

plot(asia$pop,asia$rgdpe,log = "xy",xlab="Population",ylab="GDP")


```

```{r}
library(readxl)
pwt1950sgp <- read_excel("pwt1950sgp.xlsx")
df<-pwt1950sgp
```

```{r}
## You can use the below code to generate the graph.
## Don't forget to replace the 'df' with the name
## of your dataframe

# You need the following package(s):
library("ggplot2")

# The code below will generate the graph:
graph <- ggplot(df, aes(x = year, y = percapitaGDP, colour = countrycode)) +
  geom_point()+
  geom_smooth(se = FALSE, method = 'lm') +
  theme_bw()
graph

# If you want the plot to be interactive,
# you need the following package(s):
library("plotly")
ggplotly(graph)

# If you would like to save your graph, you can use:
ggsave('my_graph.pdf', graph, width = 14, height = 14, units = 'cm')
```


# データ

```{r}
library(readxl)
df <- read_excel("asia.xlsx")

```


# ローカルでlibrary(ggplotgui)
- library(ggplotgui)をインストール
- コンソールにggplot_shiny()と打つ
- グラフ作成して、Rコードを得る。

```{r}
## You can use the below code to generate the graph.
## Don't forget to replace the 'df' with the name
## of your dataframe

# You need the following package(s):
library("ggplot2")

# The code below will generate the graph:
graph <- ggplot(df, aes(x = ctfp, y = percapitaGDP)) +
  geom_point()+
  geom_smooth(se = TRUE, method = 'lm') +
  theme_bw()
graph

# If you want the plot to be interactive,
# you need the following package(s):
library("plotly")
ggplotly(graph)

# If you would like to save your graph, you can use:
ggsave('my_graph.pdf', graph, width = 14, height = 14, units = 'cm')
```

