---
title: "PM2.5データの取得"
author: "田中 鮎夢"
date: "2023-04-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#install.packages("devtools")
#install.packages(c("doParallel", "dplyr", "methods", "parallel"))
#install.packages(c("plyr", "raster", "rlang", "sf", "tibble", "tidycensus", "tigris"))
#install.packages(c("ggplot2", "gridExtra", "knitr", "rmarkdown", "testthat"))

devtools::install_github("mitre/ACAGPM", ref = "main")
```


### 州レベル
```{r}
state_pm <- ACAGPM::pull_state_ACAG(pull_type = "Internal", 
                                    year = 2016, 
                                    level = "State", 
                                    state = c("22", "44", "45"))
head(state_pm)
```
```{r}
state_id <- ACAGPM::lookup_GEOID(tract = "9502, Abbeville, South Carolina")
print(state_id)
```
```{r, message = FALSE, results = 'hide'}
library(tidycensus)
library(ggplot2)
library(tigris)
library(gridExtra)
library(ACAGPM)

this_state <- "RI"
this_county <- "Providence"
county_geoid <- lookup_GEOID(county = "Providence, RI")
acs_populations_2016 <- tidycensus::get_acs(geography = "tract", variables = "B01003_001", year = 2016, state = "RI", county = "Providence", geometry = TRUE)
acs_populations_2016 <- acs_populations_2016 %>%
  dplyr::mutate(pop_per_sq_km = estimate / as.numeric(sf::st_area(geometry)) * 1000000) %>%
  dplyr::select(GEOID, pop_per_sq_km)
pm_2016 <- pull_tract_ACAG(pull_type = "Internal", year = 2016, level = "County", county_state = county_geoid)
pm_2016 <- pm_2016 %>%
  dplyr::select(GEOID, Particulate.Matter)
acs_pm_data <- acs_populations_2016 %>%
  dplyr::left_join(pm_2016, by = "GEOID")
```
